### ISSUE TITLE
Make "define/ inspect a type" form modal

### ISSUE THREAD

**Issue by annedino4** [hackworthltd/primer-app#103]
See #102  Because the "inspect type" page covers everything, it broke some students' mental flow, they were surprised to see the whole canvas disappeared and didn’t know what to do. After returning to the canvas, one student forgets what she was doing.

We could change it to a modal dialogue on the canvas, so it doesn't break the mental flow when defining/checking a type:

<img width="2311" alt="Screenshot 2021-10-22 at 2 07 16 pm" src="https://user-images.githubusercontent.com/76442964/138459776-b257a948-5ff0-411a-9225-a570eeef4712.png">

**Comment by georgefst** [comment]
We now render and edit typedefs on the canvas (https://github.com/hackworthltd/primer-app/pull/863, https://github.com/hackworthltd/primer-app/pull/968 etc.).
