### ISSUE TITLE
Screens of define/ insepct type redesign

### ISSUE THREAD

**Issue by annedino4** [hackworthltd/primer-app#105]
See #81, I have designed some symbols for typedef UI buttons, however, it can seem ambiguous to the students/ redundant in the UI.
<img width="299" alt="Screenshot 2021-10-25 at 2 02 29 pm" src="https://user-images.githubusercontent.com/76442964/138700089-b0049d0d-4c8c-4580-9e8e-0d98783f0c52.png">

To solve the issues, I redesigned the page with better visual hierarchy ([figma file](https://www.figma.com/file/dIs2O0X2zm2RTk36KbCoHm/Ui-Exploration-21-Oct?node-id=0%3A1)):

<img width="777" alt="Screenshot 2021-10-25 at 2 04 03 pm" src="https://user-images.githubusercontent.com/76442964/138700351-e262ecfd-f780-431c-97b1-a4b7000b57c5.png">
<img width="774" alt="Screenshot 2021-10-25 at 2 04 53 pm" src="https://user-images.githubusercontent.com/76442964/138700487-e4c05249-3949-4cee-a532-6768ada90981.png">

We should still disable "add parameters" for beginners.

**Comment by georgefst** [comment]
We now render and edit typedefs on the canvas (https://github.com/hackworthltd/primer-app/pull/863, https://github.com/hackworthltd/primer-app/pull/968 etc.).
