### ISSUE TITLE
Render the selected node's type in an inset window in the canvas

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer-app#15]
We've talked about (and more or less agreed, I think?) how it might be useful to render the selected node's type in an inset window on the canvas, rather than in the sidebar. This would relieve sidebar vertical space pressure, and would make it easy to render types as trees, if the student prefers that rendering. (Currently, in the sidebar, we can only render types as text.)

**Comment by georgefst** [comment]
This was implemented long ago.

**Comment by georgefst** [comment]
In https://github.com/hackworthltd/primer-app/pull/966, in fact.
