### ISSUE TITLE
Better rendering of case expressions

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer-app#58]
We need a better way to render case expressions than what we're currently doing. The current implementation looks like this:

<img width="303" alt="106013165-1b19fd80-60b4-11eb-8bf6-b313745ec697" src="https://user-images.githubusercontent.com/2438/106467013-f8ad2900-6493-11eb-8beb-435e8ba1faeb.png">

There are several issues here, but one chief issue is that the scrutinee, `a1`, is not visually distinguished between the branch labels, `True` and  `False`.

@hmac had some thoughts that he posted in Keybase chat, which I'll reproduce here:

<img width="734" alt="Screen Shot 2021-02-01 at 1 48 23 PM" src="https://user-images.githubusercontent.com/2438/106467144-28f4c780-6494-11eb-8d83-b9e93fdcd312.png">

The next step is to have a UX meeting to discuss some ideas, but this will have to wait until some higher-priority UX issues are addressed.

**Comment by georgefst** [comment]
This is where we've ended up:

<img width="467" alt="image" src="https://github.com/hackworthltd/primer-app/assets/12991097/2f12813a-f630-4aed-a007-a89511c96472">

I think I can safely say we're all happy with the overall approach. There is obviously room for minor improvements, but it might be time to close this issue.

**Comment by dhess** [comment]
Thanks, I'd lost track of this issue. I agree that it's time to close it. Any additional work will be tweaks and/or based on testing feedback.

**Comment by dhess** [comment]
I should say that, for the record, we ended up where we are as of 2023-10-05 based on some testing feedback. Students said they visually preferred the top-down ordering of branches, but in our testing, made fewer mistakes when the branches were ordered left-to-right.

(I do need to point out that this testing wasn't comprehensive: there were only about half a dozen test subjects (all with a few hours' previous experience with an early version of the Hackworth Codes frontend), and the test was done with static images, not a real application.)
