### ISSUE TITLE
New typedef modal: sync validation with backend

### ISSUE THREAD

**Issue by brprice** [hackworthltd/primer-app#700]
Currently the backend has some rules about what names are acceptable (they have to be unique in the appropriate sense). The frontend also has some rules, but they differ (at the very least, because the backend does not expose what constructor names already exist in any nice way! Thus checking for uniqueness is hard.) These should be brought into sync (or at least, the frontend should be stricter than the backend -- note that this logic is only for creation, not viewing. We would want the frontend to be able to view any type that the backend may give us, but viewing in general is future work)

Basic solution: improve the backend and manually implement the correct logic on the frontend. A perhaps better solution (automatically keeps in sync, but more network load): "preflight" the request -- on each change we could ask the backend "is this valid yet".

**Comment by georgefst** [comment]
Now that we've removed the form UI in favour of editing typedefs on the canvas (#863, #968 etc.), all typedef edits go through the action panel, but much of the discussion above is still relevant. If we try to enter a bad name, nothing happens and an error is logged in the console.

Perhaps this can be closed in favour of https://github.com/hackworthltd/primer-app/issues/869.

**Comment by dhess** [comment]
I think you're right.
