### ISSUE TITLE
Add symbols/icons/labels to typedef UI buttons

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer-app#81]
(This comes from @annedino4's User Research Report Round 2, issue number 2.)

We should probably add symbols/icons/labels to typedef UI buttons, just as we have them for action buttons in the editor interface. This will help students identify the button they want at a glance, rather than requiring them to read the longer descriptions.

**Comment by georgefst** [comment]
We no longer have a form UI for typedefs, and all edits go through the action panel.
