### ISSUE TITLE
Should node labels be on the upper left-hand corner of nodes?

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer-app#888]
Here's a screenshot demonstrating a few basic node types:

<img width="331" alt="Screenshot 2023-05-24 at 2 16 37 AM" src="https://github.com/hackworthltd/primer-app/assets/2438/7d4a637c-a176-4aea-913a-d69593d11380">

If you were to read those nodes out loud (or if they were rendered in text mode), you should say, "let x," and "lambda y," and "var(iable) x." But when you see them in tree mode, the labels are to the right of the variable name, so if you were a beginner, you might be inclined instead to read those as "x let," "y lambda," and "x var."

I wonder if the labels should move from the upper right-hand corner to the upper left-hand corner, so they read more naturally.

**Comment by georgefst** [comment]
Closed by https://github.com/hackworthltd/primer-app/pull/1016.
