### ISSUE TITLE
UI refactor proposal

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer-app#950]
As I've been working on UI issues for the past week now, I've had time to reflect on the current state of our UI, and our recent discussions on ways to improve it. Our current thinking is, more or less, that:

1. The sidebar is taking up too much static space, and we need to optimize for more editing space, especially on phones.
2. The sidebar is a decent place to put lists of definitions and types, but not great for showing evaluations &mdash; it can't be resized, it's often the wrong aspect ratio, etc.
3. Therefore, let’s eliminate the sidebar by breaking it into pieces:
    a. Add a search bar for searching for and listing definitions and types.
    b. Extend the floating toolbar with a new, larger window for showing type info and evaluations.
    c. Move the "add definition" and "add typedef" buttons to the action panel, where they will mix with the context-specific actions for the currently selected node.

## Problems with this approach

After consideration, I think the steps outlined in point 3 above have problems of their own:

1. The search bar would also take up static space, and would reduce vertical space available for both the canvas and the action panel, which is the dimension in which we're most challenged for space, based on our observation during testing that many students will have laptops with 16:9 aspect ratios. It would be unfortunate to lose valuable space for something that will probably be used relatively infrequently during editing tasks.
2. The search bar should be both modal and accessible, and this may be hard to do correctly with a drop-down sheet as imagined in this design. [Though to be fair, it could probably be modeled on top of a menu item drop-down, but with dynamic offerings.]
3. I've raised this concern about 3.c. above before, but by putting the "add definition" and "add typedef" buttons in the action panel, we conflate global pseudo-actions with node-contextual actions. What if the student thinks that the definition/typedef they're adding will be scoped to the expression tree rooted at the selected node? 
    a. Not only that, but this move would also use up valuable vertical space in the action panel, where we're already struggling due to the sometimes long list of available actions. We would like to *reduce* the need for scrolling to find the action you want, not make matters worse.
    b. Note that we decided to move undo, redo, and the text/tree view toggle to a separate control on the canvas (i.e., the floating toolbar), rather than adding them to the action panel, specifically to avoid these issues. I think all of those reasons apply to add def/add typedef, as well.
4. A floating toolbar of buttons as we currently have is one thing, and fairly common. (The inspiration came from image editing tools.) But adding an "appendage" window to it for displaying type info and eval seems like we're drifting towards a sort of "drawer UI" where we stick things we don't know what else to do with onto a floating UI blob. A toolbar of simple buttons and a window for rendering trees and type info seem like they should ideally be completely separate UI components.

## New proposal

After some thought, I have an alternative proposal for refactoring the current UI:

1. Eliminate the fixed sidebar as planned.
2. Implement the definition/typedef list/search as a pop-up "command palette." See [here](https://tailwindui.com/components/application-ui/navigation/command-palettes) for ideas of what I mean. I think this is an improvement over a traditional fixed search bar for the following reasons:
    a. It looks modern.
    b. It can easily go away when no longer needed, like a modal dialog. We would add a search button to the canvas in order to activate it, along with a hot key.
    c. It has a very flexible form-factor, unlike a traditional 2D line-item-based search results dropdown. For example, we could implement a tree preview alongside the selected definition; [see this example](https://tailwindui.com/components/application-ui/navigation/command-palettes#component-5e859372042e1b3b308dc51f3ac8bad6) for inspiration.
    d. It's easy to make modal and accessible, because it explicitly takes focus. It's also more intuitively modal, as it could blur the underlay (i.e., the rest of the UI) when displayed.
3. Move the redo/undo/level/view to a new control in a fixed location on the canvas, as we’ve recently done for zoom controls. They can be made unobtrusive and relatively small, and we can drop the draggable chrome in the current floating toolbar implementation.
4. Reserve the floating window idiom for type info & eval as a sort of "2nd canvas," picture-in-picture (PIP) style, which should be familiar to anyone who watches video on mobile devices while using a second app. By reserving this window for displaying trees and other complex info, we can add affordances to match:
    a. Pinch-to-zoom to zoom into/out of full window in eval mode.
    b. Resizable & variable aspect ratio.
5. For consistency with other global controls like undo/redo and zoom, make "add definition" and "add typedef" simple canvas overlay buttons.

With this approach, we’ve now eliminated all extraneous chrome, and made a lot more space available for drawing trees on the canvas. We also have a natural way to make eval a full-screen activity with a familiar transition gesture, either for interactive eval, or for viewing very large full eval results like lists and trees that would be too small to make out in the PIP.

Additionally, the action panel remains context-focused, with no mixing of global and node-specific scope. Ensuring that the offered actions don't mix global and node-specific actions also leaves the door open to removing the action panel, as well, and replacing it with some kind of pop-up menu upon node selection. Moving add def/typedef to the action panel would preclude such designs, because they wouldn't be otherwise available until you selected a node in the tree and could view the pop-up action panel.

**Comment by georgefst** [comment]
I generally really like this direction of travel.

My only slight concern is the placement of global actions. When we've discussed this recently, I have felt quite strongly that all UI elements which are used to modify the program\* should be grouped together. And I'd liked the idea of putting these at the top of the action panel, both in a single row, possibly with a separator, to indicate that they are different to local actions, and maybe even dropping the action panel's heading to reclaim further vertical space. However, I am also keen on the idea of changing the action panel to  a pop-up e.g. a pie menu, and as you've said, it really wouldn't make sense to have global actions there. So maybe we can just use some sort of common styling instead to associate the add-def/typedef buttons with the local action buttons instead.

\* Admittedly, this could strictly said to include undo, but that feels quite different to me in that it doesn't do anything original. It's not part of the mechanism by which one actually builds programs.

**Comment by dhess** [comment]
It definitely makes sense to style all pseudo-actions the same. I recently abstracted out the `ActionPanelButton` to its own standalone component, so that would be easy to do.

**Comment by dhess** [comment]
Steps 1-4 have been implemented. Step 5 is probably not compatible with the current UI design, so the global actions have been moved into the action panel after all.
